### PR TITLE
Add header background

### LINKED ISSUE #3: Add header background
At the moment, the header background is a colour. Have an option to add an image that's easy to swap to something else and works on multiple screen sizes.

### PR DESCRIPTION
**Pull request by Mayank17M**
## Changes
Adds an option to add a background image to header, which can be swapped with any other image.

Before:

image

After:
image

## Contributors

@Mayank17M @n00bmaster2810 

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by Mayank17M** [comment]
@yashika51 Can you review this?

**Review by yashika51 — APPROVED** [review]

**Comment by Mutugiii** [comment]
Looks good! Love your choice of image

Also are you also working on #14 in this PR or can I approve for merging?

**Comment by Mayank17M** [comment]
Yes, I'm working on #14, I'll create a separate PR for it in a few hours.

**Comment by Mutugiii** [comment]
Alright, though it looks like you may have pushed some of your updates for that issue on this PR

mlh_dark_mode

**Comment by Mayank17M** [comment]
Sorry, I accidentally committed to the main branch.
I've reverted the commits. Will open a new PR for #14

**Review by Mutugiii — APPROVED** [review]
Great!

**Comment by Mayank17M** [comment]
@yashika51 Can you merge this?

**Pull request merged**
