### PR TITLE
Github Action to compress images for Faster loading times

### LINKED ISSUE #2: Improve loading time for images
Currently, images take a while to load as they're quite large. Can we compress the images when they are committed using a GitHub action to improve loading speeds?

### PR DESCRIPTION
**Pull request by Mutugiii**
### Fixes #2 

A YAML config file is created using Calibre App(from GitHub Marketplace - Actions) to compress Images while maintaining high quality to improve loading speeds.

Further configuration instructions can be found [here](https://github.com/marketplace/actions/image-actions)

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by Mayank17M** [comment]
This looks good. Although I'd suggest using the [Combined Workflow](https://github.com/marketplace/actions/image-actions#combined-workflow) as it covers the edge cases and ensures the right order of task execution within Image Actions. 
When you use that template just make sure:
* Change `example/example_repo` to our repository details.
* Remove schedule from template

**Comment by Mutugiii** [comment]
Thanks for taking your time to review, I realize they are a couple of edge cases like direct pushing that need to be looked into.I'll look into it.

**Review by Mayank17M — APPROVED** [review]
LGTM!

**Comment by Mutugiii** [comment]
@yashika51 could you kindly review?

**Review by yashika51 — APPROVED** [review]

**Pull request merged**
