### PR TITLE
add Profile page for each fellow solved 

### PR DESCRIPTION
**Pull request by shamvi-05**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.
**These are the changes i have added in the main website**

Screen Shot 2022-04-06 at 7 17 47 PM

**Added all pod members**
Screen Shot 2022-04-07 at 11 40 57 AM

**Added separate description page**
Screen Shot 2022-04-06 at 7 17 58 PM

### CODE REVIEW

**Comment by shamvi-05** [comment]
Resolved Issue #9 @yashika51 could you please review it

**Comment by suraj-singh127** [comment]
@shamvi-05 The location I provided doesn't match with the one on the portfolio.
Can you please correct that?

**Comment by shamvi-05** [comment]
@suraj-singh127 Hey sure I will correct that.. I have actually intentionally  missed that part because @unnati914  is already doing the image and location part once all the PR gets merged I guess it will be corrected ..But still if you want I will do it surely.

**Comment by suraj-singh127** [comment]
Okay. That's fine!

**Comment by shamvi-05** [comment]
@suraj-singh127 I have updated the info!!

**Comment by ankitaugale23** [comment]
@shamvi-05 cpuld you change the location, it's Pune, Maharashtra, India for me instead of Delhi.

**Comment by shamvi-05** [comment]
> @shamvi-05 could you change the location, it's Pune, Maharashtra, India for me instead of Delhi.

yeah sure !

**Review by abhishekrawe — APPROVED** [review]

**Comment by shamvi-05** [comment]
Fixes #9

**Pull request merged**
