### PR TITLE
solves issue Add a map showing all the countries that fellows are loc…

### PR DESCRIPTION
**Pull request by AnushaNathRoy**
…ated in #10

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

We have added a map to show the locations of all the pod members as a pin. On clicking this pin, a popup will be displayed showing a one-liner description about the respective member.

This is important as a visual representation of location is a better representation of the location and is a pleasing UI experience for the viewers.

We have implemented the above by using Mapbox GL JS to create an interactive map and place interactive pins and popups.   Attached below is how the map looks on the website.

Screenshot 2022-04-08 at 1 55 22 AM

### CODE REVIEW

**Review by KKhushhalR2405 — APPROVED** [review]
Looks Good

**Review by OmkarAcharekar — COMMENTED** [review]
May be we can add images of all pod members on their respective locations..Except that pr looks clean

**Comment by AnushaNathRoy** [comment]
> May be we can add images of all pod members on their respective locations..Except that pr looks clean

Yeah even I thought that too but decided to push this much for this issue and opened a separate issue for that.

**Comment by AnushaNathRoy** [comment]
@yashika51 I think the PR is ready to be merged

**Review by n00bmaster2810 — APPROVED** [review]
Looks good, it can be merged.

**Comment by yashika51** [comment]
@AnushaNathRoy conflicts :)

**Comment by AnushaNathRoy** [comment]
@yashika51 I think it is ok now

**Pull request merged**
