### PR TITLE
added info about pod

### PR DESCRIPTION
**Pull request by unnati914**
Signed-off-by: Unnati <chhabraunnati324@gmail.com>
solves #13 

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Review by abhishekrawe — COMMENTED** [review]
Screenshot (321)
Screenshot (322)
Hey, @unnati914 there is some issue with responsiveness and adding pictures If You want any Help I will help you with That,

**Comment by unnati914** [comment]
Yes @abhishekrawe, I guess @suraj-singh127 is working on responsiveness and he opened up a PR too for that

**Comment by shamvi-05** [comment]
@unnati914 I have Created PR #41  with improved UI . It got merged I hope that clears your conflict! you can review it.
It looks like this!
Screen Shot 2022-04-08 at 12 26 17 AM
t

**Comment by EfazAhmed** [comment]
That looks great! I was trying to figure out how to fix the conflict with the yml file, but this looks amazing! Responsiveness was also something to consider and the overall consistency of the UI so the circular images were definitely a great contribution to the project.

**Pull request merged**
