### PR TITLE
fix: alignment for cards and social icons

### PR DESCRIPTION
**Pull request by JyotimoyKashyap**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Fixes 

Before : 
deployment

After : 
ligth

### CODE REVIEW

**Review by KKhushhalR2405 — APPROVED** [review]
LGTM

**Comment by JyotimoyKashyap** [comment]
Solved merge conflicts with the latest code with the main production.

**Comment by KKhushhalR2405** [comment]
Oops...conflicts again 😪 @JyotimoyKashyap

**Comment by JyotimoyKashyap** [comment]
> Oops...conflicts again 😪 @JyotimoyKashyap

Fixed merge conflicts again

**Pull request merged**
