### PR TITLE
Added navBar with MLH logo and animation on scrolling, as well as links to existings sections

### LINKED ISSUE #8: Add a navigation bar
As the portfolio gains more information, it may make sense to add a navigation bar. This bar should include the logo on the left side but only once the page has scrolled down a bit.

### PR DESCRIPTION
**Pull request by suraj-singh127**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Screenshot of the Navbar added - 
Navbar Screenshot

@PAOK-2001 and @Mayank17M  please review the PR

Closes #8

### CODE REVIEW

**Comment by Mayank17M** [comment]
The navbar looks much better and clean. 
A few things can be changed to make it look even better.
* Change the MLH logo to the MLH prep logo: The prep logo gives the website a better representation.
* The navbar color can be changed from white to any other color that goes well with the header background. Check out #15 for reference.
* The text size on the navbar("Meet the pod"...) can be increased as it looks smaller wrt the navbar size.

Other than this, I think this is good and the code looks clean.
Let's wait for some more people to review this!

**Comment by suraj-singh127** [comment]
Changes - 

- [x] Logo changed to MLH Prep
- [x] Increased the font size of the navbar links
- [x] Changed the color of navbar

Here's a screenshot of how it looks now - 
image

@Mayank17M @PAOK-2001 please review the changes as requested by @Mayank17M

**Comment by Mayank17M** [comment]
LGTM! 🎉

**Review by yashika51 — APPROVED** [review]

**Comment by PAOK-2001** [comment]
The Nav Bar looks great! Totally agree with the change of color! Excelent job. Looks ready

**Review by Mutugiii — APPROVED** [review]
Looks lovely!

**Comment by yashika51** [comment]
@suraj-singh127 a few conflicts, maybe merge main and look at it.

**Comment by unnati914** [comment]
@suraj-singh127 , you can clear the build cache maybe and retry the deploy again?

**Comment by yashika51** [comment]
Is this ready to get merged @suraj-singh127?

**Comment by suraj-singh127** [comment]
I am also trying to solve #20 so that it solves the profile images overflowing.

**Comment by PAOK-2001** [comment]
> I am also trying to solve #20 so that it solves the profile images overflowing.

I think you mean #31 *.

**Comment by suraj-singh127** [comment]
@yashika51 This PR is good to go!

**Pull request merged**
