### PR TITLE
Add social icons for fellows | Issue #11

### LINKED ISSUE #11: Add social icons for fellows
At the moment, it only displays the fellow name and location. To help people network, we should add social icons to each of the fellow cards.

Screenshot 2021-09-30 at 14 24 40
- [ ] Add LinkedIn icons to the card
- [ ] Add Twitter icons to the card
- [ ] Add Resume icons to the card
- [ ] Add GitHub icons to the card

### PR DESCRIPTION
**Pull request by JyotimoyKashyap**
Fixed #11  

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Tasks 
- [x] Add LinkedIn icons to the card
- [x] Add Twitter icons to the card
- [x] Add Resume icons to the card
- [x] Add GitHub icons to the card

Explanation : 
Added social media icons for each individual fellow card with dummy links for the time being.

### CODE REVIEW

**Comment by Mayank17M** [comment]
Can you include some images for reference?

**Comment by Mutugiii** [comment]
Looks good!

**Comment by JyotimoyKashyap** [comment]
> Can you include some images for reference?

You can check out the deploy preview for reference. 

Also, below is the image attached.
Screenshot 2022-04-07 234219

**Comment by Mayank17M** [comment]
Looks nice! It would look better if the gaps can be reduced between the icons.

**Pull request merged**
